name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@main
    with:
      typecheck: cp tests/config.example.ts tests/config.ts && pnpm run typecheck
      test: cp tests/config.example.ts tests/config.ts && test tests/request.test.ts
